# Importação dos Dados

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/cfneves/turma-visualizacao-de-dados/refs/heads/master/modulo-01/base_do_projeto/Base%20Varejo.csv"

df_original = pd.read_csv(url, sep=';')
df = df_original.copy()

In [2]:
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

In [4]:
df.describe()

,CO_ID,CL_ID,CL_EC,CL_FHL,PR_ID,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,830000.000000,830000.000000,830000.000000,830000.00000,830000.000000,0.0,0.0,0.0,0.0
mean,460045.089890,499.595204,2.596911,1.14654,115.051855,NaN,NaN,NaN,NaN
std,265465.247541,287.568253,1.170599,1.41696,66.129241,NaN,NaN,NaN,NaN
min,1000.000000,1.000000,1.000000,0.00000,1.000000,NaN,NaN,NaN,NaN
25%,233117.000000,254.000000,2.000000,0.00000,58.000000,NaN,NaN,NaN,NaN
50%,456517.000000,498.000000,3.000000,0.00000,115.000000,NaN,NaN,NaN,NaN
75%,690132.000000,746.000000,4.000000,2.00000,172.000000,NaN,NaN,NaN,NaN
max,919822.000000,1000.000000,5.000000,4.00000,229.000000,NaN,NaN,NaN,NaN

# Limpeza e Tratamento dos Dados

In [5]:
df = df.drop(columns=['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'])
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

## Duplicatas

In [6]:
num_duplicatas = df.duplicated().sum()
print(f'Número de linhas duplicadas no dataset: {num_duplicatas}')

Número de linhas duplicadas no dataset: 96553

In [7]:
df_limpo = df.drop_duplicates().copy()
num_duplicatas_apos = df_limpo.duplicated().sum()
print(f'Número de linhas duplicadas no dataset: {num_duplicatas_apos}')

Número de linhas duplicadas no dataset: 0

## Correção dos Tipos de Dados

In [8]:
colunas_inteiras = ['CO_ID', 'CL_ID', 'CL_EC', 'CL_FHL', 'PR_ID']
for col in colunas_inteiras:
    df_limpo[col] = pd.to_numeric(df_limpo[col], errors='coerce').astype('Int64')

In [9]:
colunas_categoricas = ['CL_GENERO', 'CL_SEG', 'PR_CAT', 'PR_NOME']
for col in colunas_categoricas:
    df_limpo[col] = df_limpo[col].astype('string').str.strip().str.upper()

In [10]:
for col in ['CL_GENERO', 'CL_SEG', 'PR_CAT', 'PR_NOME']:
    df_limpo[col] = df_limpo[col].astype('category')

In [11]:
df_limpo['DATA'] = pd.to_datetime(df_limpo['DATA'],format='%d/%m/%Y',errors='coerce')

In [12]:
print(df_limpo.isna().sum())

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

In [13]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 733447 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       733447 non-null  datetime64[ns]
 1   CO_ID      733447 non-null  Int64
 2   CL_ID      733447 non-null  Int64
 3   CL_GENERO  733447 non-null  category
 4   CL_EC      733447 non-null  Int64
 5   CL_FHL     733447 non-null  Int64
 6   CL_SEG     733447 non-null  category
 7   PR_ID      733447 non-null  Int64
 8   PR_CAT     733447 non-null  category
 9   PR_NOME    733447 non-null  category
dtypes: Int64(5), category(4), datetime64[ns](1)
memory usage: 45.5 MB

# Estatística Descritiva

In [14]:
coluna_filhos = 'CL_FHL'

media = df_limpo[coluna_filhos].mean()
mediana = df_limpo[coluna_filhos].median()
desvio_padrao = df_limpo[coluna_filhos].std()
moda = df_limpo[coluna_filhos].mode()[0]
maximo = df_limpo[coluna_filhos].max()
minimo = df_limpo[coluna_filhos].min()
contagem = df_limpo[coluna_filhos].count()

print(f'Estatísticas Descritivas para a coluna {coluna_filhos}:')
print(f'Média: {media:.2f}')
print(f'Mediana: {mediana:.2f}')
print(f'Desvio Padrão: {desvio_padrao:.2f}')
print(f'Moda: {moda}')
print(f'Máximo: {maximo}')
print(f'Mínimo: {minimo}')
print(f'Contagem: {contagem}')

Estatísticas Descritivas para a coluna CL_FHL:
Média: 1.15
Mediana: 0.00
Desvio Padrão: 1.42
Moda: 0
Máximo: 4
Mínimo: 0
Contagem: 733447

In [15]:
display(df_limpo[coluna_filhos].describe())

count    733447.0
mean     1.146049
std      1.416917
min           0.0
25%           0.0
50%           0.0
75%           2.0
max           4.0
Name: CL_FHL, dtype: Float64

In [16]:
# Quantidade de Compras por Genero de Cliente
compras_por_genero_pivot_total = pd.pivot_table(
    df_limpo,
    index='CL_GENERO',
    values='PR_ID',
    aggfunc='count')

compras_por_genero_pivot_total = compras_por_genero_pivot_total.rename(columns={'PR_ID': 'Total de Compras'})

display(compras_por_genero_pivot_total.sort_values(by='Total de Compras', ascending=False))

genero_mais_compras_total = compras_por_genero_pivot_total.idxmax()['Total de Compras']
max_compras_total = compras_por_genero_pivot_total.max()['Total de Compras']

print(f"\nO gênero com o maior número de compras é '{genero_mais_compras_total}' com {max_compras_total} compras.")

/tmp/ipykernel_53350/3519182295.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  compras_por_genero_pivot_total = pd.pivot_table(

           Total de Compras
CL_GENERO
F                    382427
M                    351020

O gênero com o maior número de compras é 'F' com 382427 compras.

In [17]:
# Quantidade de Compras por Segmento de Cliente
compras_por_segmento = pd.pivot_table(
    df_limpo,
    index='CL_SEG',
    values='PR_ID',
    aggfunc='count'
)

compras_por_segmento = compras_por_segmento.rename(columns={'PR_ID': 'Total de Compras'})

display(compras_por_segmento.sort_values(by='Total de Compras', ascending=False))

segmento_mais_compras = compras_por_segmento.idxmax()['Total de Compras']
max_compras_segmento = compras_por_segmento.max()['Total de Compras']

print(f"\nO segmento de cliente com o maior número de compras é '{segmento_mais_compras}' com {max_compras_segmento} compras.")

/tmp/ipykernel_53350/3211610364.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  compras_por_segmento = pd.pivot_table(

        Total de Compras
CL_SEG
B                 468505
C                 205265
A                  59677

O segmento de cliente com o maior número de compras é 'B' com 468505 compras.

In [18]:
# Quantidade de Compras por Categoria de Produto
compras_por_categoria = df_limpo.groupby('PR_CAT')['PR_ID'].count().reset_index()
compras_por_categoria = compras_por_categoria.rename(columns={'PR_ID': 'Total de Compras'})

display(compras_por_categoria.sort_values(by='Total de Compras', ascending=False).head(10))

/tmp/ipykernel_53350/3253754904.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  compras_por_categoria = df_limpo.groupby('PR_CAT')['PR_ID'].count().reset_index()

       PR_CAT  Total de Compras
2   ALIMENTOS            384197
4     HIGIENE            137702
5     LIMPEZA            128632
3     BEBIDAS             38264
6         PET             28553
1  ACESSORIOS             12871
0        #N/D              3228

In [19]:
# Quantidade de Compras por Número de Filhos
compras_por_filhos = df_limpo.groupby('CL_FHL')['PR_ID'].count().reset_index()
compras_por_filhos = compras_por_filhos.rename(columns={'PR_ID': 'Total de Compras'})

display(compras_por_filhos.sort_values(by='Total de Compras', ascending=False))

   CL_FHL  Total de Compras
0       0            384986
2       2             94168
3       3             92407
1       1             90845
4       4             71041

# Conclusões e Insights

Com base nas análises exploratórias realizadas até o momento, podemos extrair os seguintes insights principais e observar alguns pontos a serem considerados:

### Insights Obtidos:

1.  **Perfil de Clientes:**
    *   Clientes do gênero feminino ('F') realizam a maior quantidade de compras (382.427) em comparação com o gênero masculino ('M') (351.020).
    *   Clientes da classe 'B' são os mais ativos em termos de número total de compras (468.505), seguido pela classe 'C' e depois 'A'.
    *   Clientes sem filhos ('CL_FHL' = 0) são os que mais realizam compras, e o volume de compras tende a diminuir à medida que o número de filhos aumenta.

2.  **Categorias de Produtos:**
    *   A categoria de produtos 'ALIMENTOS' é de longe a mais vendida, com um número expressivo de 384.197 compras, destacando sua importância no mix de produtos. 'HIGIENE' e 'LIMPEZA' também são categorias fortes.

### Problemas Remanescentes e Pontos de Atenção:

1.  As análises focaram na quantidade de compras. Seria importante incluir o valor de cada compra para entender o faturamento gerado por gênero, segmento, categoria, etc.
2.  As colunas 'Unnamed: 10' a 'Unnamed: 13' foram descartadas por estarem vazias. É fundamental verificar se esses campos foram realmente irrelevantes ou se representavam dados ausentes que deveriam ter sido tratados de outra forma na coleta original.