**1 - CARREGANDO A BASE DE DADOS E EXIBINDO NÚMEROS DE REGISTROS, COLUNAS E TIPOS DE DADOS**

In [1]:
# Importando as bibliotecas necessárias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Bibliotecas importadas com sucesso!")

Bibliotecas importadas com sucesso!

In [44]:
# Carregando a base de dados do Kaggle
df = pd.read_csv("C:/Users/robso/Documents/SCTEC/Base Mini Projeto/Base varejo.csv", 
sep=";", 
encoding="cp1252", 
decimal=","
)

In [45]:
# Listando informações gerais sobre a base de dados
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB
None

In [32]:
# Listando as primeiras 5 colunas da base de dados
display(df.head())

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [33]:
# Listando as últimas 5 colunas da base de dados
display(df.tail())

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

In [34]:
# Exibindo a descrição estatística da base de dados
display(df.describe())

,CO_ID,CL_ID,CL_EC,CL_FHL,PR_ID,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,830000.00000,830000.000000,830000.000000,830000.00000,830000.000000,0.0,0.0,0.0,0.0
mean,460045.08989,499.595204,2.596911,1.14654,115.051855,NaN,NaN,NaN,NaN
std,265465.24754,287.568253,1.170599,1.41696,66.129241,NaN,NaN,NaN,NaN
min,1000.00000,1.000000,1.000000,0.00000,1.000000,NaN,NaN,NaN,NaN
25%,233117.00000,254.000000,2.000000,0.00000,58.000000,NaN,NaN,NaN,NaN
50%,456517.00000,498.000000,3.000000,0.00000,115.000000,NaN,NaN,NaN,NaN
75%,690132.00000,746.000000,4.000000,2.00000,172.000000,NaN,NaN,NaN,NaN
max,919822.00000,1000.000000,5.000000,4.00000,229.000000,NaN,NaN,NaN,NaN

**2 - VERIFICAÇÃO DOS DADOS**

In [38]:
# Exibindo valores nulos por colunas
print(df.isnull().sum())

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [ ]:
# As colunas Unnamed 10, 11, 12 e 13 estão completamente vazias.

In [43]:
# Exibindo duplicatas e mostrando as 5 primeiras colunas duplicadas
print(f"Duplicatas: {df.duplicated().sum()}")
display(df[df.duplicated()].head(5))

Duplicatas: 96553

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
19,2019-02-01,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
40,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,2019-02-01,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,2019-02-01,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,2019-02-01,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN

**3 - LIMPEZA DOS DADOS**

In [46]:
# Listando informações gerais sobre a base de dados antes do tratamento da data
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB
None

In [47]:
# Convertendo data para o formato datetime
df["DATA"] = pd.to_datetime(df["DATA"], format="%d/%m/%Y")

In [48]:
# Listando informações gerais sobre a base de dados depois do tratamento da data
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  datetime64[us]
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: datetime64[us](1), float64(4), int64(5), str(4)
memory usage: 88.7 MB
None

In [49]:
# Removendo as colunas Unnamed 10, 11, 12 e 13 devidos as mesmas não terem nenhum dado
df.drop(columns=["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"], inplace=True)

In [50]:
# Listando informações gerais sobre a base de dados depois de remover as colunas Unnamed 10, 11, 12 e 13
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  datetime64[us]
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  str
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  str
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  str
 9   PR_NOME    830000 non-null  str
dtypes: datetime64[us](1), int64(5), str(4)
memory usage: 63.3 MB
None