In [2]:
import pandas as pd
import re
from datetime import datetime

print('pandas versão:', pd.__version__)
print('Bibliotecas carregadas com sucesso! ')

pandas versão: 2.3.3
Bibliotecas carregadas com sucesso!

In [3]:
CAMINHO = 'C:\\turma-visualizacao-de-dados\\alunos\\andressa_alves\\semana_04\\base_rh.csv'
df = pd.read_csv(CAMINHO, 
                 sep=';',
                 encoding='cp1252',
                 decimal=','
                 )
print('Dados carregados com sucesso! ')
print('Número de linhas e colunas:', df.shape)
print('Número de linhas: ', df.shape[0])
print('Número de colunas: ', df.shape[1])

Dados carregados com sucesso!
Número de linhas e colunas: (1000, 10)
Número de linhas:  1000
Número de colunas:  10

In [6]:
df.head(5)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

In [8]:
df.tail(10)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
990,991,Sr. Vicente Silveira,Produção,Gerente,8026.70,11/07/2021,F,55,Viúvo,Inativo
991,992,Emanuel da Cruz,Logística,Gerente,12572.11,30/01/2024,M,33,Viúvo,Ativo
992,993,Enrico Monteiro,RH,Coordenador,14677.33,26/12/2017,M,52,Divorciado,Inativo
993,994,Ana Lívia Cardoso,RH,Coordenador,14912.48,22/10/2015,M,27,Solteiro,Inativo
994,995,Fernando Monteiro,RH,Assistente,10983.02,09/01/2023,F,42,Viúvo,Ativo
995,996,Matheus Aragão,Financeiro,Analista,11389.03,06/05/2022,F,26,Viúvo,Ativo
996,997,Ryan Martins,Financeiro,Analista,14060.42,05/06/2023,F,37,Viúvo,Ativo
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [9]:
print('Colunas do DataFrame: ')
print(df.columns.tolist())

Colunas do DataFrame:
['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   object
 2   Departamento    1000 non-null   object
 3   Cargo           1000 non-null   object
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   object
 6   Genero          1000 non-null   object
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   object
 9   Status          1000 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB

In [14]:
print('Quantidade de valores nulos por coluna: ')
df.isnull().sum()

Quantidade de valores nulos por coluna:

ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

In [15]:
print('Percentual de valores nulos por coluna: ')
print((df.isnull().sum() / len(df)) * 100)

Percentual de valores nulos por coluna:
ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

In [17]:
df.describe().round(2)

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [18]:
print('Valores únicos por coluna: ')
print(df.nunique())

Valores únicos por coluna:
ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64

In [21]:
for col in ['Departamento','Cargo','Genero','Status','Estado_Civil']:
    print(f'\n --- {col} ---:')
    print(df[col].value_counts())
    print('---')

 --- Departamento ---:
Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64
---

 --- Cargo ---:
Cargo
Coordenador    225
Gerente        221
Assistente     199
Analista       178
Técnico        177
Name: count, dtype: int64
---

 --- Genero ---:
Genero
F    510
M    490
Name: count, dtype: int64
---

 --- Status ---:
Status
Ativo      515
Inativo    485
Name: count, dtype: int64
---

 --- Estado_Civil ---:
Estado_Civil
Solteiro      265
Viúvo         261
Divorciado    240
Casado        234
Name: count, dtype: int64
---

In [25]:
df[['Nome','Cargo','Departamento']].head(10)

                   Nome        Cargo Departamento
0           Julia Nunes  Coordenador    Logística
1    Sr. Gustavo Duarte      Gerente           TI
2   Srta. Mariana Cunha  Coordenador           RH
3    Ana Sophia da Cruz      Técnico     Produção
4     Dr. Nicolas Pinto      Gerente     Produção
5         Marcela Costa     Analista           RH
6  João Miguel da Costa      Técnico     Produção
7     Gabrielly Cardoso     Analista           RH
8           Raul da Paz  Coordenador    Logística
9   Davi Lucca Teixeira      Gerente     Produção

In [27]:
df[df['Departamento'] == 'Vendas'][['Nome','Cargo','Departamento','Salario']].head(10)

                     Nome        Cargo Departamento   Salario
12           Laís da Mata     Analista       Vendas   4719.79
26       Cecília Silveira   Assistente       Vendas   5126.11
28  Srta. Ana Lívia Alves  Coordenador       Vendas  14477.24
32          Augusto Jesus   Assistente       Vendas   8686.25
34            Luana Costa  Coordenador       Vendas   5824.04
47          Maitê da Mota  Coordenador       Vendas   7727.77
50           Esther Nunes  Coordenador       Vendas   6506.85
68            Bianca Lima  Coordenador       Vendas   3742.37
70      Luiz Felipe Silva      Gerente       Vendas   2639.39
82      Vinicius da Cunha      Técnico       Vendas   5481.17

In [29]:
ativos = df[df['Status'] == 'Ativo']
print('Total de funcionários: ', len(df))
print('Número de funcionários ativos: ', len(ativos))
print('Número de funcionários inativos: ', len(df) - len(ativos))

Total de funcionários:  1000
Número de funcionários ativos:  515
Número de funcionários inativos:  485

In [30]:
inativos = df[df['Status'] == 'Inativo']
print('Total de funcionários: ', len(df))
print('Número de funcionários ativos: ', len(ativos))
print('Número de funcionários inativos: ', len(inativos))

Total de funcionários:  1000
Número de funcionários ativos:  515
Número de funcionários inativos:  485

In [31]:
gerentes_ti = df[
    (df['Cargo'] == 'Gerente') & (df['Departamento'] == 'TI')
    ]
print('Número de gerentes no departamento de TI: ', len(gerentes_ti))

gerentes_ti[['Nome','Salario','Status', 'Data_Admissao']].head(10)

Número de gerentes no departamento de TI:  31

                   Nome   Salario   Status Data_Admissao
1    Sr. Gustavo Duarte   8155.98  Inativo    29/04/2017
49    Benjamin da Costa   9766.01  Inativo    27/04/2024
130    Catarina Costela   9597.83  Inativo    03/07/2023
131       Laura Cardoso   7364.46  Inativo    29/06/2018
175       Maria Cardoso  12127.27  Inativo    22/05/2024
187   Ana Júlia Cardoso   8738.63    Ativo    30/05/2021
247         Ian Pereira   2395.32    Ativo    10/05/2019
273   Ana Clara Peixoto   7301.14    Ativo    16/11/2019
296      Augusto Santos   8237.80  Inativo    26/08/2021
307     Manuela Barbosa   7015.91    Ativo    21/06/2017

In [36]:
print(f'Salário médio : R$ {df["Salario"].mean():.2f}')
print(f'Salário mínimo : R$ {df["Salario"].min():.2f}')
print(f'Salário máximo : R$ {df["Salario"].max():.2f}')
print(f'Salário mediano : R$ {df["Salario"].median():.2f}')

Salário médio : R$ 8579.95
Salário mínimo : R$ 2000.71
Salário máximo : R$ 14954.51
Salário mediano : R$ 8571.13