In [ ]:
# Estudos relacionados a semana 4. Todos os códigos foram refeitos e comentados

import pandas as pd
import re # expressões regulates (para limpar texto)
from datetime import datetime # bib para trabalhar com datas

# testando as importações
print('Pandas versão:', pd.__version__)
print('Bibliotecas importadas')

Pandas versão: 2.3.3
Bibliotecas importadas

In [3]:
# importando o arquivo CSV - locao do arquivo CSV
CAMINHO = R"C:\turma-visualizacao-de-dados\alunos\sergio_leite\semana_04\base_rh.csv"

# pd.read_csv vai ler e add os dados de leitura a variavel df que será usada para acessar o arquivo e gerar dados

df = pd.read_csv(
    CAMINHO,
    sep=';', # padrão de ; para separar colunas e não virgula
    encoding='cp1252', # encoding do windows para leitura de acentos
    decimal=',' # add padrão de virgula para separar decimais
)

print('Dados carregados corretamente')
print(f'Total de linhas: {df.shape[0]}') # df.shape[0] se refere ao numero de linhas
print(f'Total de colunas: {df.shape[1]}') # df.shape[1] se refere ao numero de colunas

Dados carregados corretamente
Total de linhas: 1000
Total de colunas: 10

In [ ]:
print('Seguem as 5 primeiras linhas') # ajuda a verificar se as linhas iniciais foram lidas corretamente
print(df.head(5)) # chama a var df e solicita os 5 primeiras linhas do inicio

print('Seguem as últimas 5 linhas') # ajuda a verificar se as linhas finais foram lidas corretamente
print(df.tail(5)) # solicita ao df as últimas 5 linhas

Seguem as 5 primeiras linhas
   ID_Funcionario                 Nome Departamento        Cargo   Salario  \
0               1          Julia Nunes    Logística  Coordenador   9088.34
1               2   Sr. Gustavo Duarte           TI      Gerente   8155.98
2               3  Srta. Mariana Cunha           RH  Coordenador  14027.93
3               4   Ana Sophia da Cruz     Produção      Técnico   6647.97
4               5    Dr. Nicolas Pinto     Produção      Gerente   8730.19

  Data_Admissao Genero  Idade Estado_Civil   Status
0    13/08/2024      F     43     Solteiro  Inativo
1    29/04/2017      F     59     Solteiro  Inativo
2    11/12/2024      F     27   Divorciado    Ativo
3    16/06/2019      M     50       Casado  Inativo
4    29/03/2019      F     62       Casado  Inativo
Seguem as últimas 5 linhas
     ID_Funcionario                Nome Departamento     Cargo   Salario  \
995             996      Matheus Aragão   Financeiro  Analista  11389.03
996             997        Ryan Martins   Financeiro  Analista  14060.42
997             998   Isabelly Ferreira           TI   Gerente   2348.73
998             999       Thales Farias     Produção  Analista   9430.62
999            1000  Sra. Maysa Costela     Produção   Técnico  12549.72

    Data_Admissao Genero  Idade Estado_Civil   Status
995    06/05/2022      F     26        Viúvo    Ativo
996    05/06/2023      F     37        Viúvo    Ativo
997    29/12/2023      F     58     Solteiro  Inativo
998    25/12/2019      M     41     Solteiro    Ativo
999    14/11/2022      M     46        Viúvo  Inativo

In [14]:
# df.columns mostra as colunas do dataset
# tolist transforma o index de colunas em uma lista e ajuda a acessar para fazer modificações em nomes, por exemplo.

print(df.columns.tolist()) # mostra as colunas do dataset

['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [ ]:
matriz_dados = df.values.tolist() # cria a matriz de dados sendo uma lista python com todos os dados do dataframe

print(matriz_dados[80]) # imprime a matriz na linha 80

[81, 'Gabriela Freitas', 'Logística', 'Analista', 5573.44, '16/03/2021', 'F', 65, 'Divorciado', 'Ativo']

In [ ]:
# df.info() faz o resumo completo do DF em um comando
# mostra o nome de cada coluna, quantidade de valores nao nulos, tipos de dados (dtype), uso de memoria 
# é um comando muito útil para um primeiro diagnóstico da base de dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   object
 2   Departamento    1000 non-null   object
 3   Cargo           1000 non-null   object
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   object
 6   Genero          1000 non-null   object
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   object
 9   Status          1000 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB

In [ ]:
# para saber a quantidade de dados nulos no DF
# o df.isnull cria uma tabela true / false onde ons true são os nulos
# .sum() vai somar os true de cada coluna (true 1 e false 0)

print('Quantidade de dados nulos por coluna no data frame')
print(df.isnull().sum())
print() # pular uma linha

# calculando o percentual de nulos
# len(df) vai pegar a quandidade de linhas do DF
# calcular o percentual de nulos é muito útil em grandes bases para entender a proporção de nulos

print('O percentual de nulos no DF é: ')
print((df.isnull().sum() / len(df) * 100).round(2))

Quantidade de dados nulos por coluna no data frame
ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

O percentual de nulos no DF é:
ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

In [ ]:
# O describe() é muito usado para ver a estatistica descritiva das colunas numéricas 
# ajuda a confirmar que dados estão no formato esperado, sem valores absurdos e sem erros de leituras ou outros erros.
# count - quantos valores não nulos existem
# mean - média
# std - Desvio padrão - o quanto os valores variam em torno da média
# min - Menor valor
# 25% - 25% dos registros estão abaixo desse valor
# 50% - mediana. 50% dos registros abaixo de 50%
# 75% - 75% dos registros estão abaixo desse valor
# max - Maior valor

df.describe().round(2) # o round(2) limita o valor a 2 casas decimais

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [ ]:
# Explorando colunas
# # df.nunique() vai mostrar valores únicos por coluna
# Ajuda a identificar quais são categorias (poucas opções) e quais sao identificadores (muitas opções diferentes)
# nunique() - conta quantos valores diferentes existem 
# value_counts() mostra a distribuição - quantas vezes cada valor aparece
print('Valores únicos por coluna')
print(df.nunique())

Valores únicos por coluna
ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64

In [53]:
# Explorando colunas
# df['Salario'].value_counts() #  conta quantas vezes cada valor apaece na coluna escolhida

for col in ['Departamento', 'Cargo', 'Genero', 'Status', 'Estado_Civil']:
    print(f'\n --- {col} ---')
    print(df[col].value_counts())

 --- Departamento ---
Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64

 --- Cargo ---
Cargo
Coordenador    225
Gerente        221
Assistente     199
Analista       178
Técnico        177
Name: count, dtype: int64

 --- Genero ---
Genero
F    510
M    490
Name: count, dtype: int64

 --- Status ---
Status
Ativo      515
Inativo    485
Name: count, dtype: int64

 --- Estado_Civil ---
Estado_Civil
Solteiro      265
Viúvo         261
Divorciado    240
Casado        234
Name: count, dtype: int64

In [ ]:
# Selecionando colunas e filtrando linhas
# df['Nome'] - seleciona a coluna
# df['Nome', 'Salario'] - Seleciona váriadas colunas
# df[df['Status'] == 'Ativo'] - Filtra de linhas

df['Departamento'].head(3) # lista os 3 primeiros departamentos
df['Departamento'].value_counts() # conta quantas vezes o valor aparece repetido na coluna

Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64

In [ ]:
# Selecionando multiplas colunas

df[['Nome', 'Cargo', 'Departamento']].value_counts()

df[['Nome', 'Cargo', 'Departamento']].head(10)

                   Nome        Cargo Departamento
0           Julia Nunes  Coordenador    Logística
1    Sr. Gustavo Duarte      Gerente           TI
2   Srta. Mariana Cunha  Coordenador           RH
3    Ana Sophia da Cruz      Técnico     Produção
4     Dr. Nicolas Pinto      Gerente     Produção
5         Marcela Costa     Analista           RH
6  João Miguel da Costa      Técnico     Produção
7     Gabrielly Cardoso     Analista           RH
8           Raul da Paz  Coordenador    Logística
9   Davi Lucca Teixeira      Gerente     Produção

In [12]:
# Filtro simples: Seleciona somente as linhas onde o status == 'Ativo'
# df['Status'] == 'Ativo' - cria uma serie true / false
# df[True / False] = mantém so as linhas true

ativos = df[df['Status'] == 'Ativo']
print(f'Total de funcionários: {len(df)}')
print(f'Funcionários ativos: {len(ativos)}')
print(f'Funcionários inativos: {len(df) - len(ativos)}')

Total de funcionários: 1000
Funcionários ativos: 515
Funcionários inativos: 485

In [25]:
# Filtro composto: Testa duas condições ao mesmo tempo
# Usar & para AND (as duas condições devem ser verdadeiras)
# Usar | para OR (uma ou outra deve ser verdadeira)
# Sintaxe: Casa condição deve estar entre parenteses

gerentes_de_ti = df[(df['Cargo'] == 'Gerente') & (df['Departamento'] == 'TI')]
print(f'A quantidades de getentes de TI é: {len(gerentes_de_ti)}')
gerentes_de_ti[['Nome', 'Cargo', 'Salario']].head(5)

A quantidades de getentes de TI é: 31

                   Nome    Cargo   Salario
1    Sr. Gustavo Duarte  Gerente   8155.98
49    Benjamin da Costa  Gerente   9766.01
130    Catarina Costela  Gerente   9597.83
131       Laura Cardoso  Gerente   7364.46
175       Maria Cardoso  Gerente  12127.27

In [33]:
# Estatísticas em uma coluna nomérica
# .mean() - média
# .min() - menor valor
# .max() - maior valor
# .median() - mediana - o valor do meio quando ordenado
print(f'{df['Salario'].mean():,.2f}')
print(df['Salario'].max())
print(df['Salario'].min())
print(df['Salario'].median())

8,579.95
14954.51
2000.71
8571.134999999998

In [ ]:
# exportando celula para o formato JSON
# Json é o formato padrão de troca de dados entre sistemas modernos - APIs, ERPs na nuvem, dashboards web
# JSON - JavaScript Object Notation
# Abaixo um exemplo de como ficaria o resultado apos a conversão para o formato JSON
[
    {'Nome': 'Julia Nunes',
     'Departamento': 'Logistica',
     'Salario': 9088.34},
    {'Nome': 'Gustavo Duarte',
     'Departamento': 'TI',
     'Salario': 8155.98}
]

[{'Nome': 'Julia Nunes', 'Departamento': 'Logistica', 'Salario': 9088.34},
 {'Nome': 'Gustavo Duarte', 'Departamento': 'TI', 'Salario': 8155.98}]

In [47]:
import json # Biblioteca nativa do python para manipular JSON
# df - variavel que importou a base de dados
# to_json - converte para JSON e salva no arquivo
# df.to_json - converta a base de dados df para json

df.to_json(
    'base_rh.json', # nome da base de dados que será criada
    orient='records', # define o formato Json e o record define que cada linha vire um objeto
    force_ascii=False, # evita que caracteres acentuados brasileiros (á, é, ç , etc) sejam convertidoa para UNICODE e se tornem ilegiveis. Mantém o formato brasileiro.
    indent=2 # add quebra de linha e 2 espaços de recuo. Sem isso o PANDAS criaria todo o JSON em uma unica linha gigante.
)

print('base_rh.json gerado com sucesso!')

df_json = pd.read_json('base_rh.json') # função pandas PD para ler o arquivo JSON
print(len(pd.read_json('base_rh.json'))) # Faz a contagem de quantas linhas tem o arquivo
# print(f'linhas lidas do json: {len(df_json)}')

with open('base_rh.json', 'r', encoding='utf-8') as f: # Abre o arquivo baserh.json com o parametro 'r' de read e a codificação brasileira para nao perder acentos e chamou esse arquivo de F
#o with garante que o python feche o arquivo automaticamente após terminar, para não trabar o computador
    amostra = json.load(f) # Pega o texto puro que esta em f e transforma em uma lista de dicionários comum do python e guarda na var amostra
print('\nPrimeiros 4 registro do JSON:')

# json.dumps - pega a lista do python e transforma de volta em um texto formatado para exibição
# ensure_ascii=False e indent=4 servem para manter acentos e deixar o texto alinhado com espaços
print(json.dumps(amostra[:4], ensure_ascii=False, indent=4))

base_rh.json gerado com sucesso!
1000

Primeiros 4 registro do JSON:
[
    {
        "ID_Funcionario": 1,
        "Nome": "Julia Nunes",
        "Departamento": "Logística",
        "Cargo": "Coordenador",
        "Salario": 9088.34,
        "Data_Admissao": "13/08/2024",
        "Genero": "F",
        "Idade": 43,
        "Estado_Civil": "Solteiro",
        "Status": "Inativo"
    },
    {
        "ID_Funcionario": 2,
        "Nome": "Sr. Gustavo Duarte",
        "Departamento": "TI",
        "Cargo": "Gerente",
        "Salario": 8155.98,
        "Data_Admissao": "29/04/2017",
        "Genero": "F",
        "Idade": 59,
        "Estado_Civil": "Solteiro",
        "Status": "Inativo"
    },
    {
        "ID_Funcionario": 3,
        "Nome": "Srta. Mariana Cunha",
        "Departamento": "RH",
        "Cargo": "Coordenador",
        "Salario": 14027.93,
        "Data_Admissao": "11/12/2024",
        "Genero": "F",
        "Idade": 27,
        "Estado_Civil": "Divorciado",
        "Status": "Ativo"
    },
    {
        "ID_Funcionario": 4,
        "Nome": "Ana Sophia da Cruz",
        "Departamento": "Produção",
        "Cargo": "Técnico",
        "Salario": 6647.97,
        "Data_Admissao": "16/06/2019",
        "Genero": "M",
        "Idade": 50,
        "Estado_Civil": "Casado",
        "Status": "Inativo"
    }
]

In [58]:
# Exportando para Excel
# Pode ser exportação simples com uma aba ou avançado com várias abas por departamento

# exportação simples:
df.to_excel('base_rh.xlsx', index=False, sheet_name='Funcionários')
print('base_rh.xlsx criada com sucesso!')

# exportação avançada (uma aba por departamento) - criou o arquivo .xlsx e chamou de writer
with pd.ExcelWriter('base_rh_por_departamento.xlsx', engine='openpyxl') as writer:

# primeira aba do dataset completo
# tranformou para excel, chamou o nome (apelido) writer, criou a Aba com nome Todos e colocou todos os registros nela
    df.to_excel(writer, sheet_name='Todos', index=False)
    print('Aba Todos: todos os registros')


# df['Departamento'].unique() cria a lista de departamento sem repetição 
# sorted é uma função para colocar em ordem alfabética
    for depto in sorted(df['Departamento'].unique()):

# filtrando os funcionários do departamento
        df_depto = df[df['Departamento'] == depto]

# cria um filtro de limite por conta do limite do excel para o nome da aba 31 caracteres
        nome_aba = depto[:31]

        df_depto.to_excel(writer, sheet_name=nome_aba, index=False)
        print(f'  Aba "{nome_aba}": {len(df_depto)} registros')

print('base_rh_por_departamento.xlsx criada com sucesso!')

base_rh.xlsx criada com sucesso!
Aba Todos: todos os registros
  Aba "Financeiro": 189 registros
  Aba "Logística": 156 registros
  Aba "Produção": 182 registros
  Aba "RH": 166 registros
  Aba "TI": 147 registros
  Aba "Vendas": 160 registros
base_rh_por_departamento.xlsx criada com sucesso!

In [76]:
# Manipulação de datas - Módulo datetime
# Quando importamos dados de arquivos CSV, excel ou Json, as datas sempre entram
# no python como se fossem texto comum (string) e não uma data. 
# A coluna data de admissão foi criada como uma string
# strptime - string parse time - transforma texto para date
# strftime - string format time - transforma data para texto
# Códigos de formato da tela:
    # %d: Dia com dois dígitos (ex: 08)
    # %m: Mês com dois dígitos (ex: 08)
    # %Y: (Y MAIUSCULO) Ano com 4 dígitos (ex: 2024) -> Nota: Y maiúsculo é para 4 dígitos, y minúsculo seria apenas para 2 dígitos (24).
    # %B: Nome do mês por extenso (ex: Agosto)

# importação da biblioteca
from datetime import datetime, timedelta

# o primeiro valor da coluna data de admissão será o exemplo
data_texto = '13/08/2024' 
# datetime.strptime(texto, formato)
# %d/%m/%y

# de TEXTO para DATA - strptime
#criamos a var para receber o datetime com o modelo do texto e o formato da data
data_obj = datetime.strptime(data_texto, '%d/%m/%Y')
print(f'String original: {data_texto}')
print(f'Objeto datetime: {data_obj}')
print(f'O tipo da data é: {type(data_obj)}')
print() # pular 1 linha

# de Data para TEXTO - strftime
# vamos formatar o texto na forma que quisermos
formatado = data_obj.strftime('%d de %B de %Y')
print(f'A data formatada ficou assim: {formatado}')

# extraindo parte da data
print(f"Dia {data_obj.day}")
print(f"Mês {data_obj.month}")
print(f"Ano {data_obj.year}")

String original: 13/08/2024
Objeto datetime: 2024-08-13 00:00:00
O tipo da data é: <class 'datetime.datetime'>

A data formatada ficou assim: 13 de August de 2024
Dia 13
Mês 8
Ano 2024

In [ ]:
# timesdelta - É o resultado da subtração de duas datas, a diferença de tempo.
# se subtrair as datas, recebemos o timedelta como resultado

# datetime.today
hoje = datetime.today()
print(hoje)
print()

diferenca = hoje - data_obj # calculo do timedelta usando o valor atribuido a var data_obj
print(f'A diferenca entre a data de hoje {hoje} e a data \n  {data_obj} é igual a {hoje}')
print()
print(f'Data de admissão: {data_texto}')
print(f'Hoje é dia: {hoje.strftime("%d/%m/%Y")}') # usando o strftime ele converta a data para o formato desejado
print(f'A diferença entre as datas é de: {diferenca.days} dias') # ao colocar o .days ele vai mostrar apenas os dias
print(f'A diferença em anos é de {diferenca.days / 365.25:.1f} anos') # para criar anos, temos que usar os dias como base e calcular com o .25 por conta dos anos bissestos

2026-05-25 20:15:56.395015

A diferenca entre a data de hoje 2026-05-25 20:15:56.395015 e a data
  2024-08-13 00:00:00 é igual a 2026-05-25 20:15:56.395015

Data de admissão: 13/08/2024
Hoje é dia: 25/05/2026
A diferença entre as datas é de: 650 dias
A diferença em anos é de 1.8 anos

In [ ]:
# Convertendo uma coluna inteira com o pd.to.datetime
# Usado para converser muitas linhas ao mesmo tempo.
# O exemplo anterior converteu apenas 1 linha

print(f'Tipo da data ANTES: {df['Data_Admissao'].dtype}')
print(f'Valor da data ANTES: {df['Data_Admissao'].iloc[0]}') # iloc[0] acessa a 1ª linha do indice
print()

# Agora vamos converter toda a coluna e usar uma cópia  para nao alterar o DF original
df_limpo = df.copy() # Criamos uma copia independente do DF na var df_limpo para trabalhar sem mexer no original
df_limpo['Data_Admissao'] = pd.to_datetime( 
    df_limpo['Data_Admissao'],
    format='%d/%m/%Y', # define o formato que queremos para a string de entrada
    errors='coerce' # define que datas invalidas viram Nat (Not a Time) e nao erro
)

print(f'O valor NOVO é: {df_limpo['Data_Admissao'].iloc[0]}') # imprime o df na data de admissão e no indice 0
print(f'O tipo NOVO é: {df_limpo["Data_Admissao"].dtype}')
print(f'Os Nats gerados foram: {df_limpo["Data_Admissao"].isna().sum()}')  # isna() vai listar todos os NaTs e o sum vai somar e dar um resoltado final

Tipo da data ANTES: object
Valor da data ANTES: 13/08/2024

O valor NOVO é: 2024-08-13 00:00:00
O tipo NOVO é: datetime64[ns]
Os Nats gerados foram: 0

In [140]:
# Extraindo informações com o acessor .dt.
# Depois de converter para o datetime p pandas libera o acessor .dt para acessar as datas
# .dt.year - retorna o ano (2026)
# .dt.month - retorna o mês (10)
# .dt.quarter - retorna o trimestre (3)
# .dt.day_name() - retorna o dia da semana ("monday")

# criando colunas derivadas da data 
df_limpo['Ano_Admissao'] = df_limpo['Data_Admissao'].dt.year
df_limpo['Mes_Admissao'] = df_limpo['Data_Admissao'].dt.month
df_limpo['Trimestre'] = df_limpo['Data_Admissao'].dt.quarter

# print(df_limpo['Ano_Admissao']) # testando a coluna criada

# calculando o tempo de casa em anos
# print(pd.Timestamp.today()) # comando para imprimir a data e hora de hoje no pandas

# calculando o tempo de casa em anos
hoje_ts = pd.Timestamp.today() # atribui a data de hoje na var


# criamos a tabela tempo_casa_anos e atribuimos a ela o calculo da data de:
#  hoje (hoje_ts) - o acesso a data de admissão em dias. Dividimos por 365.25 para considerar o ano bisexto
df_limpo['Tempo_Casa_Anos'] = (
    (hoje_ts - df_limpo['Data_Admissao']).dt.days / 365.25).round(2)
print(df_limpo['Tempo_Casa_Anos'].iloc[2])

# montando uma lista com o resultado
cols = ['Nome', 'Data_Admissao', 'Ano_Admissao', 'Mes_Admissao', 'Trimestre', "Tempo_Casa_Anos"]
df_limpo[cols].head(5)

1.45

,Nome,Data_Admissao,Ano_Admissao,Mes_Admissao,Trimestre,Tempo_Casa_Anos
0,Julia Nunes,2024-08-13,2024,8,3,1.78
1,Sr. Gustavo Duarte,2017-04-29,2017,4,2,9.07
2,Srta. Mariana Cunha,2024-12-11,2024,12,4,1.45
3,Ana Sophia da Cruz,2019-06-16,2019,6,2,6.94
4,Dr. Nicolas Pinto,2019-03-29,2019,3,1,7.16

In [ ]:
# Uando função
# def nome_funcao(parametro):
#    return resultado

# construindo uma função para classificar o tempo de casa em uma categoria de texto
# é interessante criar categoriar pois é mais fácil para utilizar com gráficos e filtros no power BI do que números decimais

def classificar_tempo(anos):
    """
    Recebe: Anos (número) e o tempo de casa do funcionário
    Retorna: Uma categoria em texto
    """
    # pd.isna() - verifica se o valor é nulo (NaN ou NaT)
    if pd.isna(anos):
        return 'Sem data'
    elif anos < 1:
        return 'Menos de 1 ano'
    elif anos < 3:
         return '1 a 3 anos'
    elif anos < 5:
        return '3 a 5 anos'
    else:
        return 'Mais de 5 anos'
    
# teste da função com valores individuais 
print(classificar_tempo(7))

Mais de 5 anos

In [154]:
# Aplicando a função em cada linha da coluna
# Fazendo loop em cada celular de forma eficiente

df_limpo['Faixa_Tempo_Casa'] = df_limpo['Tempo_Casa_Anos'].apply(classificar_tempo)

print('Distribuição por faixa de tempo na casa')
print(df_limpo['Faixa_Tempo_Casa'].value_counts())

Distribuição por faixa de tempo na casa
Faixa_Tempo_Casa
Mais de 5 anos    537
3 a 5 anos        217
1 a 3 anos        213
Menos de 1 ano     33
Name: count, dtype: int64