### Carregamento dos Dados

In [265]:
import pandas as pd
import numpy as np

In [266]:
# importando a base de dados e modificando os tipos de dados para o ideal em cada coluna.

df  = pd.read_csv('Base Varejo.csv', sep=';', dtype= {'CO_ID':str,'CL_ID':str,'CL_GENERO':'category','CL_FHL':int,'CL_SEG':'category','PR_ID':str,'PR_CAT':'category'})

# criaçao da copia da nossa base de dados

df_copy = df.copy()

# alterando o formato da coluna 'DATA', para '#d/#m/#Y pois estava no formato m%/%d/%Y

df['DATA'] = pd.to_datetime(df['DATA'], format='%d/%m/%Y')

In [267]:
# recolhendo amostras
df_copy.sample(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
539934,22/06/2021,595062,590,M,4,3,B,192,HIGIENE,FIXADOR,NaN,NaN,NaN,NaN
339895,27/08/2020,375763,108,M,1,0,B,80,HIGIENE,HASTES FLEXIVEIS,NaN,NaN,NaN,NaN
787559,30/06/2022,874533,398,F,4,1,B,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
218747,02/05/2020,244603,185,F,3,0,C,24,ALIMENTOS,COPA SUINA,NaN,NaN,NaN,NaN
64673,23/04/2019,72080,737,F,2,1,C,103,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
237164,03/07/2020,263163,950,M,3,0,C,173,ALIMENTOS,LINGUICA,NaN,NaN,NaN,NaN
415713,30/12/2020,457285,429,M,4,0,C,72,HIGIENE,CONDICIONADOR,NaN,NaN,NaN,NaN
15209,02/05/2019,17756,512,M,4,0,B,180,ALIMENTOS,LEITE,NaN,NaN,NaN,NaN
763822,23/05/2022,849622,666,F,2,2,B,77,HIGIENE,FIXADOR,NaN,NaN,NaN,NaN
129818,23/08/2019,145120,73,M,1,0,A,98,LIMPEZA,DESENGORDURANTE,NaN,NaN,NaN,NaN

In [268]:
# verificaçao de tipos de dados

df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  str
 2   CL_ID        830000 non-null  str
 3   CL_GENERO    830000 non-null  category
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  category
 7   PR_ID        830000 non-null  str
 8   PR_CAT       830000 non-null  category
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: category(3), float64(4), int64(2), str(5)
memory usage: 72.0 MB

### Identificando Problemas

In [269]:
# verificaçao com precentual de nulos:

print((df_copy.isnull().sum() / len(df_copy) * 100).round(2))

DATA             0.0
CO_ID            0.0
CL_ID            0.0
CL_GENERO        0.0
CL_EC            0.0
CL_FHL           0.0
CL_SEG           0.0
PR_ID            0.0
PR_CAT           0.0
PR_NOME          0.0
Unnamed: 10    100.0
Unnamed: 11    100.0
Unnamed: 12    100.0
Unnamed: 13    100.0
dtype: float64

In [270]:
# verificando duplicatas

df_copy.duplicated().sum()

# iremos logo resolver este problema em questao

np.int64(96553)

### Tratamento e Limpeza dos Dados

In [271]:
# exibiçao em dataframe, para analisarmos melhor a questao das duplicatas

# filtra a base, mostrando as linhas que possuem copias iguais
duplicatas = df_copy[df_copy.duplicated(keep=False)]

# como queremos descobrir se a questao das duplicatas tem algo haver com o id do cliente e o id do produto as ordemos dessa forma para  que facilite nossa analise
duplicatas.sort_values(by=['CO_ID', 'PR_ID']).head(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
34,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
51,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN

Apos analisar os indices, descobrimos um padrao, como da para observar, os numeros dos indices estao espaçados, oque provavelmente significa que ao passar no caixa os produtos, eles foram sendo passados de maneira meio espaçada (de acordo com o indice), oque significa que nao foi um erro do sistema, entao a compra dos produtos esta correta, e a questao das linhas duplicadas, atesta que nao ha erro algum, caso apagassemos, iriamos perder uma grande quantidade de dados valiossimos para a empresa em questao

In [272]:
# apos a analise anterior, decidimos criar uma nova coluna de quantidade, contendo as linhas duplicadas

coluna = df_copy.columns.tolist()
df_copy = df_copy.groupby(coluna, dropna=False).size().reset_index(name='QTD_PR')

df_copy[df_copy['CO_ID'] == '1000'].head(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,QTD_PR
2320,01/02/2019,1000,534,M,4,1,C,108,LIMPEZA,REMOVEDOR,NaN,NaN,NaN,NaN,1
2321,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN,2
2322,01/02/2019,1000,534,M,4,1,C,121,ALIMENTOS,UVA,NaN,NaN,NaN,NaN,1
2323,01/02/2019,1000,534,M,4,1,C,123,LIMPEZA,TIRA MANCHA,NaN,NaN,NaN,NaN,1
2324,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN,2
2325,01/02/2019,1000,534,M,4,1,C,132,HIGIENE,SABONETE,NaN,NaN,NaN,NaN,1
2326,01/02/2019,1000,534,M,4,1,C,135,LIMPEZA,RODO,NaN,NaN,NaN,NaN,1
2327,01/02/2019,1000,534,M,4,1,C,136,ALIMENTOS,RICOTA,NaN,NaN,NaN,NaN,1
2328,01/02/2019,1000,534,M,4,1,C,143,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN,1
2329,01/02/2019,1000,534,M,4,1,C,149,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN,1

In [273]:
# removendo colunas inteiramente vazias, pois nao fara sentido ter elas dentro da nossa base de dados que posteriormente sera utilizada por alguem:
df_copy = df_copy.drop(columns= ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'])

In [274]:
# correcao de inconssisetncias nas colunas PR_CAT e PR_NOME

df_copy['PR_CAT'] = df_copy['PR_CAT'].str.capitalize()
df_copy['PR_NOME'] = df_copy['PR_NOME'].str.capitalize()

In [275]:
# modificando o estado civil para estar condizente com a documentaçao e as regras de negocio da empresa:

map_df = {1:'Casado/Uniao Estavel', 2:'Divorciado', 3:'Separado', 4:'Solteiro', 5:'Viuvo'}
df_copy['CL_EC'] = df_copy['CL_EC'].map(map_df)

In [276]:
# vendo quantas linhas temos valores nulos/ausentes ou #N/D
df_copy[df_copy['PR_CAT'] == '#n/d'].shape[0]

3228

In [277]:
# vamos substituir a string '#N/D' por valores nulos, pois na etapa de verificaçao nao foi constatado
df_copy['PR_CAT'] = df_copy['PR_CAT'].replace('#n/d', np.nan)
df_copy['PR_NOME'] = df_copy['PR_NOME'].replace('#n/d', np.nan)

# removendo nulos
df_copy = df_copy.dropna(subset=['PR_CAT', 'PR_NOME'])

# transformando novamente o PR_CAT em categoria
df_copy['PR_CAT'] = df_copy['PR_CAT'].astype('category')

Removemos os valores nulos apos analisar as colunas PR_CAT, PR_NOME e PR_ID pois com os dados atuais se torna impossivel de recuperar esses 3.228 valores nulos/ausentes, iremos remover eles pois como sao poucos e nao tem maneira alguma de os recuperar, nao farao falta na nossa base

#### deixar aqui por enqanto

In [278]:
# Filtra apenas colunas de texto (object), categorias (category) e texto (strings)
df_copy.describe(include=['object', 'category', 'str'])

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_SEG,PR_ID,PR_CAT,PR_NOME
count,730219,730219,730219,730219,730219,730219,730219,730219,730219
unique,333,18469,1000,2,5,3,228,6,117
top,21/08/2020,832193,822,F,Separado,B,51,Alimentos,Presunto cozido
freq,4084,81,1527,380735,188238,466441,3322,384197,12719

### Estatísticas Descritivas

In [279]:
# filtraremos apenas colunas de texto (object), categorias (category) e texto (strings)
df_copy.describe(include=['object', 'category', 'str'])

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_SEG,PR_ID,PR_CAT,PR_NOME
count,730219,730219,730219,730219,730219,730219,730219,730219,730219
unique,333,18469,1000,2,5,3,228,6,117
top,21/08/2020,832193,822,F,Separado,B,51,Alimentos,Presunto cozido
freq,4084,81,1527,380735,188238,466441,3322,384197,12719

In [ ]:
# analise descritiva da colunas colunas 'CL_FHL' e 'QTD_PR' (criada nesta analise)
df_copy.describe()

              CL_FHL         QTD_PR
count  730219.000000  730219.000000
mean        1.145979       1.131647
std         1.416859       0.374190
min         0.000000       1.000000
25%         0.000000       1.000000
50%         0.000000       1.000000
75%         2.000000       1.000000
max         4.000000       6.000000

### Analise Exploratorio e Agrupamentos

In [ ]:
# queremos descobrir qual segmento de cliente mais compra
vendas_segmento = df_copy.groupby('CL_SEG')['PR_ID'].count().reset_index()
vendas_segmento = vendas_segmento.rename(columns={'PR_ID': 'Quantidade_Vendida'})

vendas_segmento

  CL_SEG  Qquantidade_Vendida
0      A                59416
1      B               466441
2      C               204362

In [ ]:
# queremos descobrir agora, qual genero compra mais em cada categoria de produtos

vendas_categoria = df_copy.groupby('CL_GENERO')[['PR_CAT']].count().reset_index()
vendas_categoria = vendas_categoria.rename(columns={'PR_CAT': 'Q'})